from __future__ import annotations

from typing import List

from fastapi import APIRouter

from app.core.models import FixSuggestion
from app.storage import db

router = APIRouter()


@router.get("/fixes", response_model=List[FixSuggestion])
def get_fixes() -> List[FixSuggestion]:
    """Return all fix suggestions generated by the last verification run."""
    return db.all_fixes()
